package com.certoclav.app.database;

import com.j256.ormlite.field.DatabaseField;

import static com.certoclav.app.database.Profile.FIELD_CLOUD_ID;

/**
 * Created by musaq on 7/26/2017.
 */

public class DeletedProfileModel {

    DeletedProfileModel() {
        // needed by ormlite
    }

    public DeletedProfileModel(String cloudId) {
        this.cloudId = cloudId;
    }

    // id is generated by the database and set on the object automatically
    @DatabaseField(generatedId = true, columnName = "profile_id")
    private int profile_id;

    @DatabaseField(columnName = FIELD_CLOUD_ID)
    private String cloudId;

    public String getCloudId() {
        return cloudId;
    }


}
