package com.certoclav.app.database;



import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
@DatabaseTable(tableName = "messages")
public class Message {

	// id is generated by the database and set on the object automatically


	Message(){
		
	}
	


	@DatabaseField(generatedId = true, columnName = "message_id")
	private int message_id;

	@DatabaseField(columnName = "text_head")
	private String textHead;

	@DatabaseField(columnName = "text_body")
	private String textBody;

	@DatabaseField(columnName = "cloud_id")
	private String cloudId;
	
	public String getCloudId() {
		return cloudId;
	}


	public void setCloudId(String cloudId) {
		this.cloudId = cloudId;
	}





	public Message(String cloudId, String textHead, String textBody, Controller controller) {
		super();
		this.cloudId = cloudId;
		this.textHead = textHead;
		this.textBody = textBody;
		this.controller = controller;
	}
	

	public int getMessage_id() {
		return message_id;
	}

	public void setMessage_id(int message_id) {
		this.message_id = message_id;
	}

	public String getTextHead() {
		return textHead;
	}

	public void setTextHead(String textHead) {
		this.textHead = textHead;
	}

	public String getTextBody() {
		return textBody;
	}

	public void setTextBody(String textBody) {
		this.textBody = textBody;
	}
	
	@DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = "controller") 
	private Controller controller;	
	
	

}




