package com.certoclav.app.database;



import com.j256.ormlite.field.DatabaseField;

/**
 * A simple demonstration object we are creating and persisting to the database.
 */
public class Profile {
	public static final String FIELD_INDEX = "index";
	public static final String FIELD_CLOUD_ID = "cloud_id";
	public static final String FIELD_IS_LOCAL = "isLocal";

	// id is generated by the database and set on the object automatically
	@DatabaseField(generatedId = true, columnName = "profile_id")
	private int profile_id;

	@DatabaseField(columnName = "is_visible")
	private Boolean isVisible;

	@DatabaseField(columnName = FIELD_CLOUD_ID)
	private String cloudId;

	@DatabaseField(columnName = "version")
	private int version;

	@DatabaseField(columnName = "name")
	private String name;

	
	
	@DatabaseField(columnName = "vacuum_times")
	private int vacuumTimes;
	
	@DatabaseField(columnName = "sterilisation_time")
	private int sterilisationTime;
	
	@DatabaseField(columnName = "sterilisation_temp")
	private int sterilisationTemperature;

	@DatabaseField(columnName = "sterilisation_pressure")
	private int sterilisationPressure;

	@DatabaseField(columnName = "vaccum_persist_time")
	private int vacuumPersistTime;
	
	@DatabaseField(columnName = "vaccum_persist_temp")
	private int vacuumPersistTemperature;
	
	@DatabaseField(columnName = "dry_time")
	private int dryTime;	
	
	
	
	
	public int getVacuumTimes() {
		return vacuumTimes;
	}

	public void setVacuumTimes(int vacuumTimes) {
		this.vacuumTimes = vacuumTimes;
	}

	public int getSterilisationTime() {
		return sterilisationTime;
	}

	public void setSterilisationTime(int sterilisationTime) {
		this.sterilisationTime = sterilisationTime;
	}

	public int getSterilisationTemperature() {
		return sterilisationTemperature;
	}

	public int getSterilisationPressure() {
		return sterilisationPressure;
	}

	public void setSterilisationPressure(int sterilisationPressure) {
		this.sterilisationPressure = sterilisationPressure;
	}

	public int getVacuumPersistTime() {
		return vacuumPersistTime;
	}

	public void setVacuumPersistTime(int vacuumPersistTime) {
		this.vacuumPersistTime = vacuumPersistTime;
	}

	public void setSterilisationTemperature(int sterilisationTemperature) {
		this.sterilisationTemperature = sterilisationTemperature;
	}

	public int getVacuumPersistTemperature() {
		return vacuumPersistTemperature;
	}

	public void setVacuumPersistTemperature(int vacuumPersistTemperature) {
		this.vacuumPersistTemperature = vacuumPersistTemperature;
	}

	public int getDryTime() {
		return dryTime;
	}

	public void setDryTime(int dryTime) {
		this.dryTime = dryTime;
	}

	@DatabaseField(columnName = "description")
	private String description;
	
	@DatabaseField(columnName = FIELD_IS_LOCAL)
	private Boolean isLocal;

	@DatabaseField(foreign = true, foreignAutoRefresh = true, columnName = "controller_id") 
	private Controller controller;
	
	
	/*
	 * Profile index between [1 and 7] . Only neccassary for Multicontrol and Essential version
	 */
	@DatabaseField(columnName = FIELD_INDEX)
	private int index;	
	

	
	
	//Ein ForeigenCollectionField ist ein extra feature
	//Es erlaubt eine Collection von Commands zu der Profil-Tabelle hinzuzufügen:
	//Immer wenn ein Profil bei einer query zurückgegeben wird, wird eine zweite Anfrage über 
	//die Command-Tabelle ausgeführt. Diese ermittelte Collection von fremden Commands wird 
	//dem zurückgegebenen Account hinzugefügt.
	//
	//eager==false, also haben wir eine lazy connection
	//bei lazy connections sollte man nur den iterator() und den toArray() mehtoden benutzen wegen performance
	//
	//wenn von einem Profil aus auf ein command zugegriffen wird, der in ForeignCollection eingespeichert ist,
	//und man ändert einen Wert von diesen command, dann reicht es nicht nur den profil-table upzudaten um die änderung permanent zu speichern,
	//sondern die updatefunktion des foreigncollection.:
	//for(Command command : profil1.commands()){
	//command.changeTemp(130);
	//profil1.commands.update(command);
	//}
	
	
	public Boolean getIsLocal() {
		return isLocal;
	}

	public void setIsLocal(Boolean isLocal) {
		this.isLocal = isLocal;
	}
	public int getVersion() {
		return version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public String getCloudId() {
		return cloudId;
	}

	public void setCloudId(String cloudId) {
		this.cloudId = cloudId;
	}
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}


	public Boolean getIsVisible() {
		return isVisible;
	}

	public void setIsVisible(Boolean isVisible) {
		this.isVisible = isVisible;
	}




	



	Profile() {
		// needed by ormlite
	}

	public Profile(String cloudId, int version, String name, int vacuumTimes, int sterilisationTime, int sterilisationTemperature, int sterilisationPressure, int vacuumPersistTime, int dryTime, String description, Boolean isLocal, Boolean isVisible, Controller controller, Integer index) {
		this.cloudId = cloudId;
		this.version = version;
		this.description = description;
		this.name = name;
		this.vacuumTimes = vacuumTimes;
		this.sterilisationTime = sterilisationTime;
		this.sterilisationTemperature = sterilisationTemperature;
		this.sterilisationPressure = sterilisationPressure;
		this.vacuumPersistTime = vacuumPersistTime;
		this.dryTime = dryTime;
		this.isLocal = isLocal;
		this.index = index;
		this.isVisible = isVisible;
		this.controller = controller;
	}




	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getVisible() {
		return isVisible;
	}

	public void setVisible(Boolean visible) {
		this.isVisible = visible;
	}
	
	public int getProfile_id() {
		return profile_id;
	}

	public void setProfile_id(int profile_id) {
		this.profile_id = profile_id;
	}








	public int getIndex() {
		return index;
	}

	public void setIndex(int index) {
		this.index = index;
	}






}




