package com.certoclav.app.database;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;


/**
 * Join table which links users to their posts.
 * 
 * <p>
 * For more information about foreign objects, see the <a href="http://ormlite.com/docs/foreign" >online docs</a>
 * </p>
 */
@DatabaseTable(tableName = "usercontroller")
public class UserController {

	public final static String USER_ID_FIELD_NAME = "user_id";
	public final static String CONTROLLER_ID_FIELD_NAME = "post_id";

	/**
	 * This id is generated by the database and set on the object when it is passed to the create method. An id is
	 * needed in case we need to update or delete this object in the future.
	 */
	@DatabaseField(generatedId = true)
	int id;

	// This is a foreign object which just stores the id from the User object in this table.
	@DatabaseField(foreign = true, columnName = USER_ID_FIELD_NAME)
	User user;

	// This is a foreign object which just stores the id from the Post object in this table.
	@DatabaseField(foreign = true, columnName = CONTROLLER_ID_FIELD_NAME)
	Controller controller;

	UserController() {
		// for ormlite
	}

	public UserController(User user, Controller controller) {
		this.user = user;
		this.controller = controller;
	}
}